# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  database: fish
  timeout: 5000

development:
  <<: *default
  database: fish-dev

test:
  <<: *default
  database: fish-test

production:
  <<: *default
  database: fish-prod
